In [1]:
#importing libraries
import numpy as np   
import pandas as pd
import os

import seaborn as sns
import matplotlib.pyplot as plt   
import matplotlib.style
plt.style.use('classic')

import warnings
warnings.filterwarnings("ignore")

In [2]:
#importing the data file 
df = pd.read_csv("Credit card fraud detection us.csv")
df

customer ID Trans date & time                            merchant  \
0              0  01-01-2019 00:00          fraud_Rippin, Kub and Mann   
1              1  01-01-2019 00:00     fraud_Heller, Gutmann and Zieme   
2              2  01-01-2019 00:00                fraud_Lind-Buckridge   
3              3  01-01-2019 00:01  fraud_Kutch, Hermiston and Farrell   
4              4  01-01-2019 00:03                 fraud_Keeling-Crist   
..           ...               ...                                 ...   
995          995  01-01-2019 12:38                fraud_Beier and Sons   
996          996  01-01-2019 12:39                   fraud_Pouros-Haag   
997          997  01-01-2019 12:39                fraud_O'Keefe-Wisoky   
998          998  01-01-2019 12:39                    fraud_Mohr-Bayer   
999          999  02-01-2019 12:39                    fraud_Mohr-Bayer   

          category  amount first name  last name  gender  \
0         misc_net    4.97    Jennifer      Banks      F   
1      grocery_pos  107.23   Stephanie       Gill      F   
2    entertainment  220.11      Edward    Sanchez      M   
3    gas_transport   45.00      Jeremy      White      M   
4         misc_pos   41.96       Tyler     Garcia      M   
..             ...     ...         ...        ...    ...   
995           home   43.73      Philip       Hart      M   
996   shopping_pos    7.98      Monica     Tucker      F   
997    food_dining    2.86  Jacqueline      Curry      F   
998   shopping_net   41.23     Felicia      Combs      F   
999   shopping_net   42.23     Felicia      Combs      F   

                            street                   city state    zip  \
0                   561 Perry Cove         Moravian Falls    NC  28654   
1     43039 Riley Greens Suite 393                 Orient    WA  99160   
2         594 White Dale Suite 530             Malad City    ID  83252   
3      9443 Cynthia Court Apt. 038                Boulder    MT  59632   
4                 408 Bradley Rest               Doe Hill    VA  24433   
..                             ...                    ...   ...    ...   
995           97405 Vazquez Plains             Montgomery    AL  36111   
996          302 Christina Islands           Smiths Grove    KY  42171   
997                3047 Jeff Place               Marathon    TX  79842   
998  825 Martinez Springs Apt. 625  White Sulphur Springs    WV  24986   
999  826 Martinez Springs Apt. 625  White Sulphur Springs    WV  24986   

     City pop                                job         Dob  \
0        3495          Psychologist, counselling  09-03-1988   
1         149  Special educational needs teacher  21-06-1978   
2        4154        Nature conservation officer  19-01-1962   
3        1939                    Patent attorney  12-01-1967   
4          99     Dance movement psychotherapist  28-03-1986   
..        ...                                ...         ...   
995    214703                Chemist, analytical  07-10-1994   
996      6841                  Therapist, sports  06-06-1999   
997       498                      Lexicographer  23-11-1990   
998      5216       Community development worker  05-10-1993   
999      5216       Community development worker  06-10-1993   

                            Trans num  approved  
0    0b242abb623afc578575680df30655b9         0  
1    1f76529f8574734946361c461b024d99         0  
2    a1a22d70485983eac12b5b88dad1cf95         0  
3    6b849c168bdad6f867558c3793159a81         0  
4    a41d7549acf90789359a9aa5346dcb46         0  
..                                ...       ...  
995  c5f6d4b1ac5f1caba326608f0cf293fa         0  
996  bc909cd211ddb4d3f6511abee1423324         0  
997  c882715837e35bc8a69be786678ea147         0  
998  368a6a87fcbe04ab4f040e35e3b7d734         0  
999  368a6a87fcbe04ab4f040e35e3b7d735         1  

[1000 rows x 17 columns]

In [3]:
#dataset informations
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   customer ID        1000 non-null   int64  
 1   Trans date & time  1000 non-null   object 
 2   merchant           1000 non-null   object 
 3   category           1000 non-null   object 
 4   amount             1000 non-null   float64
 5   first name         1000 non-null   object 
 6   last name          1000 non-null   object 
 7   gender             1000 non-null   object 
 8   street             1000 non-null   object 
 9   city               1000 non-null   object 
 10  state              1000 non-null   object 
 11  zip                1000 non-null   int64  
 12  City pop           1000 non-null   int64  
 13  job                1000 non-null   object 
 14  Dob                1000 non-null   object 
 15  Trans num          1000 non-null   object 
 16  approved           1000 n

In [4]:
#checking the number of missing values in each column
df.isnull().sum()


customer ID          0
Trans date & time    0
merchant             0
category             0
amount               0
first name           0
last name            0
gender               0
street               0
city                 0
state                0
zip                  0
City pop             0
job                  0
Dob                  0
Trans num            0
approved             0
dtype: int64

In [6]:
#basic summary statistics 
df.describe()

customers          amt           zip      city_pop     is_fraud
count  1000.000000  1000.000000   1000.000000  1.000000e+03  1000.000000
mean    499.500000    78.353000  49229.773000  7.965590e+04     0.001000
std     288.819436   113.087197  27039.038234  2.525460e+05     0.031623
min       0.000000     1.030000   1330.000000  2.300000e+01     0.000000
25%     249.750000    19.865000  25091.750000  6.912500e+02     0.000000
50%     499.500000    58.970000  48404.500000  2.348000e+03     0.000000
75%     749.250000    93.187500  72018.750000  1.905400e+04     0.000000
max     999.000000  1636.870000  99783.000000  2.906700e+06     1.000000

In [9]:
#distribution of legit and fraudulent transactions
df['customers'].value_counts()

0      1
671    1
658    1
659    1
660    1
      ..
338    1
339    1
340    1
341    1
999    1
Name: customers, Length: 1000, dtype: int64

In [11]:
df['amt'].value_counts()

1.13     4
7.77     3
8.34     2
3.06     2
59.56    2
        ..
57.47    1
50.16    1
4.10     1
2.67     1
42.23    1
Name: amt, Length: 957, dtype: int64

In [12]:
df.isnull().sum()

customers                0
trans_date_trans_time    0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
city_pop                 0
job                      0
dob                      0
trans_num                0
is_fraud                 0
dtype: int64

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

# Load the dataset
data = pd.read_csv("Credit card fraud detection us.csv")

# One-hot encode categorical variables
data_encoded = pd.get_dummies(data, drop_first=True)

# Assuming the target variable is the last column after encoding
X = data_encoded.iloc[:, :-1]  # Features
y = data_encoded.iloc[:, -1]   # Target variable

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features by removing the mean and scaling to unit variance
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize and train the KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

# Predict on the test set
y_pred = knn.predict(X_test_scaled)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.995
Confusion Matrix:
 [[199   0]
 [  1   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       199
           1       0.00      0.00      0.00         1

    accuracy                           0.99       200
   macro avg       0.50      0.50      0.50       200
weighted avg       0.99      0.99      0.99       200



In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the dataset
data = pd.read_csv("Credit card fraud detection us.csv")

# One-hot encode categorical variables
data_encoded = pd.get_dummies(data, drop_first=True)

# Assuming the target variable is the last column after encoding
X = data_encoded.iloc[:, :-1]  # Features
y = data_encoded.iloc[:, -1]   # Target variable

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the Random Forest Classifier
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest.fit(X_train, y_train)

# Predict on the test set
y_pred = random_forest.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.995
Confusion Matrix:
 [[199   0]
 [  1   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       199
           1       0.00      0.00      0.00         1

    accuracy                           0.99       200
   macro avg       0.50      0.50      0.50       200
weighted avg       0.99      0.99      0.99       200



In [27]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc

In [28]:
# Load the dataset
data = pd.read_csv("Credit card fraud detection us.csv")


In [31]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y_binary, test_size=0.2, random_state=42)

In [32]:
# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [33]:
# Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [34]:
# Evaluate the model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 73.03%


In [36]:
# evaluate the model
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[36 13]
 [11 29]]

Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.73      0.75        49
           1       0.69      0.72      0.71        40

    accuracy                           0.73        89
   macro avg       0.73      0.73      0.73        89
weighted avg       0.73      0.73      0.73        89

